select*from customerbehave

--Total revenue generated by male vs female  

SELECT "Gender", 
       SUM("Purachase_amount") AS revenue
FROM customerbehave
GROUP BY "Gender";

--Find those customer that used discound but they but they spent more than average purchase amount 
select "Customer_id", "Purachase_amount" 
from customerbehave 
where "Discount_applied" = 'Yes' and "Purachase_amount" >=(select avg("Purachase_amount") from customerbehave)

-- Top 5 product highesh average rating 
select "Item_purchased" ,Round(avg("Review_rating":: numeric),2) as "Average_rating" 
from customerbehave 
group by "Item_purchased"
order by avg("Review_rating") desc 
limit 5

-- Compare  the average purchase amount between standard and express shipping
select "Shipping_type", Round(avg("Purachase_amount":: numeric),2) from customerbehave
where "Shipping_type" In ('Standard','Express')
group by "Shipping_type"

--Compare Average Spend and Total revenue between Subscriber and non-subscriber
select "Subscription_status",
count("Customer_id") as Total_Customer,
Round(Avg("Purachase_amount"),2)as Average_spend,
Sum("Purachase_amount") as Total_revenue
from customerbehave
group by "Subscription_status"
order by Average_spend,Total_revenue desc

-- Top 5 product have highesh percentage with discount applied 
select "Item_purchased",
Round(100*Sum(case when "Discount_applied" = 'Yes' Then 1 else 0 end)/count(*),2) as discount_rate
from customerbehave 
group by "Item_purchased"
order by discount_rate desc
limit 5

--Checking our customer interaction from previous purchase   if customer first time purchase then 1 else if customer more than 2 purchased then its called returning 
WITH customer_interaction AS (
    SELECT 
        "Customer_id",
        "Previous_purchases",
        CASE
            WHEN "Previous_purchases" = 1 THEN 'New'
            WHEN "Previous_purchases" BETWEEN 1 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segments
    FROM customerbehave
)
SELECT 
    customer_segments, 
    COUNT(*) AS total_customer
FROM customer_interaction
GROUP BY customer_segments;

--Top 3 most product parchase within each category 
WITH item_count AS (
    SELECT
        "Category",
        "Item_purchased",
        COUNT("Customer_id") AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY "Category"
            ORDER BY COUNT("Customer_id") DESC
        ) AS item_rank
    FROM customerbehave 
    GROUP BY "Category", "Item_purchased"
)
SELECT 
    item_rank,
    "Category",
    "Item_purchased",
    total_orders
FROM item_count
WHERE item_rank <= 3

--Customer who are repeat buyers more than 5 check from subscriber 
select "Subscription_status", count("Customer_id")as repeat_buyers
from customerbehave
where "Previous_purchases" >5 
group by "Subscription_status"

 --Distribution Revenue between age group 
Select "Age" , Sum("Purachase_amount") AS Total_Revenue
from customerbehave
group by "Age"
order by Total_Revenue desc

